// Manifest for the responsive WebP sets generated by
// scripts/optimize-images.mjs from design/raw-images (see design.md for the
// image-pack mappings). All raw sources are 1376x768.
export type ImageAsset = {
  base: string
  widths: number[]
  width: number
  height: number
  alt: string
}

const HERO_WIDTHS = [640, 1280, 1376]
const CARD_WIDTHS = [480, 960, 1376]

function asset(base: string, widths: number[], alt: string): ImageAsset {
  return { base, widths, width: 1376, height: 768, alt }
}

export const heroFarmlandClean = asset(
  'hero-farmland-clean',
  HERO_WIDTHS,
  'Aerial view of Australian broadacre cropping country at golden hour, paddock boundaries tracing the rolling hills',
)

export const heroFarmlandUiOverlay = asset(
  'hero-farmland-ui-overlay',
  HERO_WIDTHS,
  'Aerial farmland at golden hour with a floating soil-analytics card',
)

export const dronePaddocks = asset(
  'drone-paddocks',
  CARD_WIDTHS,
  'Survey drone in flight above green paddocks criss-crossed by farm tracks',
)

export const agronomistSoilSampling = asset(
  'agronomist-soil-sampling',
  CARD_WIDTHS,
  'Agronomist driving a soil corer into a stubble paddock',
)

export const soilRootsMacro = asset(
  'soil-roots-macro',
  CARD_WIDTHS,
  'Macro view of a soil profile with fine roots and moisture droplets',
)

export const wetlandBillabongAerial = asset(
  'wetland-billabong-aerial',
  CARD_WIDTHS,
  'Aerial view of a billabong winding through restored wetland vegetation',
)

export const contourRevegetationAerial = asset(
  'contour-revegetation-aerial',
  CARD_WIDTHS,
  'Aerial view of contoured, revegetated slopes on a rehabilitated mine site',
)

export const soilLabAnalysis = asset(
  'soil-lab-analysis',
  CARD_WIDTHS,
  'Laboratory bench with beakers of graded soil samples, a precision balance and a spectrometer',
)

export const weatherStationField = asset(
  'weather-station-field',
  CARD_WIDTHS,
  'Solar-powered weather and soil monitoring station standing in a bare paddock',
)

export const riverMeanderAerial = asset(
  'river-meander-aerial',
  CARD_WIDTHS,
  'Aerial view of a river meandering in broad loops through golden hills',
)

// Placeholder for IMAGE 02 (Satellite Intelligence) — derived from the
// river-meander aerial with a subtle analysis overlay. Swap the raw PNG for
// the real Gemini render (design/gemini-satellite-prompt.md) and re-run
// scripts/optimize-images.mjs.
export const satelliteIntelligence = asset(
  'satellite-intelligence',
  CARD_WIDTHS,
  'Satellite view of Australian farmland with traced paddock boundaries and a subtle analysis overlay',
)

export function srcSetFor(image: ImageAsset) {
  return image.widths
    .map((w) => `/images/${image.base}-${w}.webp ${w}w`)
    .join(', ')
}

export function srcFor(image: ImageAsset) {
  const w = image.widths[Math.floor(image.widths.length / 2)]
  return `/images/${image.base}-${w}.webp`
}
