// Manifest for the responsive WebP sets generated by
// scripts/optimize-images.mjs from design/raw-images (see design.md for the
// image-pack mappings). All raw sources are 1376x768.
export type ImageAsset = {
  base: string
  widths: number[]
  width: number
  height: number
  alt: string
}

const HERO_WIDTHS = [640, 1280, 1376]
const CARD_WIDTHS = [480, 960, 1376]

function asset(base: string, widths: number[], alt: string): ImageAsset {
  return { base, widths, width: 1376, height: 768, alt }
}

export const heroFarmlandClean = asset(
  'hero-farmland-clean',
  HERO_WIDTHS,
  'Aerial view of Australian broadacre cropping country at golden hour, paddock boundaries tracing the rolling hills',
)

export const heroFarmlandUiOverlay = asset(
  'hero-farmland-ui-overlay',
  HERO_WIDTHS,
  'Aerial farmland at golden hour with a floating soil-analytics card',
)

export const dronePaddocks = asset(
  'drone-paddocks',
  CARD_WIDTHS,
  'Survey drone in flight above green paddocks criss-crossed by farm tracks',
)

export const agronomistSoilSampling = asset(
  'agronomist-soil-sampling',
  CARD_WIDTHS,
  'Agronomist driving a soil corer into a stubble paddock',
)

export const soilRootsMacro = asset(
  'soil-roots-macro',
  CARD_WIDTHS,
  'Macro view of a soil profile with fine roots and moisture droplets',
)

export const wetlandBillabongAerial = asset(
  'wetland-billabong-aerial',
  CARD_WIDTHS,
  'Aerial view of a billabong winding through restored wetland vegetation',
)

export const contourRevegetationAerial = asset(
  'contour-revegetation-aerial',
  CARD_WIDTHS,
  'Aerial view of contoured, revegetated slopes on a rehabilitated mine site',
)

export const soilLabAnalysis = asset(
  'soil-lab-analysis',
  CARD_WIDTHS,
  'Laboratory bench with beakers of graded soil samples, a precision balance and a spectrometer',
)

export const weatherStationField = asset(
  'weather-station-field',
  CARD_WIDTHS,
  'Solar-powered weather and soil monitoring station standing in a bare paddock',
)

export const riverMeanderAerial = asset(
  'river-meander-aerial',
  CARD_WIDTHS,
  'Aerial view of a river meandering in broad loops through golden hills',
)

export const satelliteIntelligence = asset(
  'satellite-intelligence',
  CARD_WIDTHS,
  'True-nadir satellite view of Australian farmland with traced paddock boundaries and sampling points',
)

// Same scene as satellite-intelligence but with no baked-in annotations —
// used as the dashboard map base so the live overlay layers are the only
// graphics on it.
export const satelliteBaseClean = asset(
  'satellite-base-clean',
  CARD_WIDTHS,
  'True-nadir satellite view of Australian farmland, paddock patchwork crossed by a tree-lined creek',
)

export const winterCropAerial = asset(
  'winter-crop-aerial',
  CARD_WIDTHS,
  'Drone view of emerald winter crops divided by red access tracks, mist lifting off the paddocks',
)

export const microbialLifeMacro = asset(
  'microbial-life-macro',
  CARD_WIDTHS,
  'Extreme macro of backlit root hairs and fungal threads weaving through dark soil aggregates',
)

export const mineSiteMonitoring = asset(
  'mine-site-monitoring',
  CARD_WIDTHS,
  'Two field workers with a tablet inspecting revegetation rows on a rehabilitated mine slope',
)

// BASE_URL is '/' in dev and '/<repo>/' when built for GitHub Pages.
const BASE = import.meta.env.BASE_URL

export function srcSetFor(image: ImageAsset) {
  return image.widths
    .map((w) => `${BASE}images/${image.base}-${w}.webp ${w}w`)
    .join(', ')
}

export function srcFor(image: ImageAsset) {
  const w = image.widths[Math.floor(image.widths.length / 2)]
  return `${BASE}images/${image.base}-${w}.webp`
}
